language: haskell

ghc:
  - 7.8

script:
  - cabal configure --enable-tests --enable-library-coverage && cabal build && cabal test
  - cabal check
  - cabal sdist
  - cabal install doctest
  - ./test-docs.sh

after_script:
  - cabal install hpc-coveralls
  - hpc-coveralls --exclude-dir=test --display-report --print-response spec
